name: cosmetics
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_assets_generator: ^0.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  lottie: null
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/
    - assets/lottie/
